### PR TITLE
Website - Favicon and Open Graph Protocols

### LINKED ISSUE #19: Title: Add Favicon
### Are you a JWOC participant?

Yes , I am Ankit Majee JWOC Mentee

### Is your feature request related to a problem? Please describe.

Yes , my feature will give a new look and design into the website 

### Describe the solution you'd like.

Designing a logo which will be displayed on the icon of the website 

### Describe alternatives you've considered.

We can add project icon or will create a brand new one which will fit the project theme .

### Add any other context or screenshots about the feature request here.

image
image

### PR DESCRIPTION
**Pull request by rakesh-vajrapu**
Closes Issue #19 

Added Favicon to the website and I have also added Open Graph Protocols to the website

- [✔ ] CodePeak 2023 Participant
- [✔ ] Contributor

Closes: #19 that will be closed through this PR

Added Favicon to the website and also added Open Graph Protocols to the website.

- Added Open Graph Protocol (OGP) meta tags for title, description, image, URL, and type.
- Added Twitter Card meta tags for Twitter-specific card properties.
- Included other meta tags for SEO: description, keywords, and author.
- Maintained existing favicon and stylesheet links.
- Ensured proper code organization and formatting.

- [ ✔] My code follows the guidelines of this project.
- [ ✔] I have performed a self-review of my code.
- [ ✔] I have commented on my code, particularly wherever it was hard to understand.
- [ ✔] I have made corresponding changes to the documentation.
- [ ✔] My changes generate no new warnings.
- [ ✔] I have added tests that prove my fix is effective or that my feature works.
- [ ✔] Any dependent changes have been merged and published in downstream modules.

## Screenshots

Screenshot (47)

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly don't submit a PR without creating an issue and getting it assigned. @rakesh-vajrapu

**Comment by rakesh-vajrapu** [comment]
> Kindly don't submit a PR without creating an issue and getting it assigned. @rakesh-vajrapu 

Sure, next time I'll follow the right format. Sorry about that! Please merge this PR!

**Comment by prathimacode-hub** [comment]
> > Kindly don't submit a PR without creating an issue and getting it assigned. @rakesh-vajrapu
> 
> Sure, next time I'll follow the right format. Sorry about that! Please merge this PR!

Ok, I will merge the PR. I want issue to be linked with PR before merging it. Kindly create an issue now and get it assigned. @rakesh-vajrapu

**Comment by rakesh-vajrapu** [comment]
Done @prathimacode-hub 

> > > Kindly don't submit a PR without creating an issue and getting it assigned. @rakesh-vajrapu
> > 
> > 
> > Sure, next time I'll follow the right format. Sorry about that! Please merge this PR!
> 
> OK, I will merge the PR. I want the issue to be linked with PR before merging it. Kindly create an issue now and get it assigned. @rakesh-vajrapu

Created issue #32 for this PR. Kindly review and merge it. And kindly add these PR points under CodePeak'23

**Review by prathimacode-hub — APPROVED** [review]
Good add-up done. @rakesh-vajrapu

**Pull request merged**
