### PR TITLE
3d game

### PR DESCRIPTION
**Pull request by Tushar98644**
## Related Issue 

- Info about the related issue 

- [x] Code Peak Participant 
- [x] Contributor

Closes:  issue #7 
### Describe the changes you've made

I have created a 3d game using html and javascript
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

I have verified this by running it on my own browser

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Screenshot 2022-12-16 at 11 54 50 AM

### CODE REVIEW

**Comment by Tushar98644** [comment]
@Kumar-Ankit56  kindly review it....

**Comment by Kumar-Ankit56** [comment]
@Tushar98644 you need to remove the BMI calci file, It is coming because you have created your both pr with the same branch. So it whould be better to create different branch for different pull request.

**Comment by Tushar98644** [comment]
> @Tushar98644 you need to remove the BMI calci file, It is coming because you have created your both pr with the same branch. So it whould be better to create different branch for different pull request.

no i have generated pr with diff branch ....kindly check the details...

**Comment by Kumar-Ankit56** [comment]
> > @Tushar98644 you need to remove the BMI calci file, It is coming because you have created your both pr with the same branch. So it whould be better to create different branch for different pull request.
> 
> no i have generated pr with diff branch ....kindly check the details...

but as I'm able to observe in the file changed option of your created pr there is extra file expect 3d game..

**Comment by Tushar98644** [comment]
> > > @Tushar98644 you need to remove the BMI calci file, It is coming because you have created your both pr with the same branch. So it whould be better to create different branch for different pull request.
> > 
> > 
> > no i have generated pr with diff branch ....kindly check the details...
> 
> but as I'm able to observe in the file changed option of your created pr there is extra file expect 3d game..


ok i will make the changes and update it....

**Comment by Kumar-Ankit56** [comment]
> > > > @Tushar98644 you need to remove the BMI calci file, It is coming because you have created your both pr with the same branch. So it whould be better to create different branch for different pull request.
> > > 
> > > 
> > > no i have generated pr with diff branch ....kindly check the details...
> > 
> > 
> > but as I'm able to observe in the file changed option of your created pr there is extra file expect 3d game..
> 
> ok i will make the changes and update it....

Yeah

**Comment by Tushar98644** [comment]
> > > > > @Tushar98644 you need to remove the BMI calci file, It is coming because you have created your both pr with the same branch. So it whould be better to create different branch for different pull request.
> > > > 
> > > > 
> > > > no i have generated pr with diff branch ....kindly check the details...
> > > 
> > > 
> > > but as I'm able to observe in the file changed option of your created pr there is extra file expect 3d game..
> > 
> > 
> > ok i will make the changes and update it....
> 
> Yeah

i have created seperate files for bmi and 3d game....pls check

**Pull request closed without merging**
