### PR TITLE
BMI Calculator

### PR DESCRIPTION
**Pull request by Tushar98644**
## Related Issue 

- Info about the related issue 

- [x] Code Peak Participant 
- [x] Contributor

Closes: issue #5 
### Describe the changes you've made

I have a added a BMI calculator to the website

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I myself ran the code on a browser and verified it....

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

Screenshot 2022-12-16 at 9 43 33 AM

### CODE REVIEW

**Comment by Tushar98644** [comment]
@prathimacode-hub kindly review my pr for issue #6

**Comment by Kumar-Ankit56** [comment]
> @prathimacode-hub kindly review my pr for issue #6

@Tushar98644 Kindly follow the PR template from the readme,

**Comment by Tushar98644** [comment]
> _ No description provided. _



> > @prathimacode-hub kindly review my pr for issue #6
> 
> @Tushar98644 Kindly follow the PR template from the readme, to get your pr reviewed.

updated ...kindly check

**Comment by Kumar-Ankit56** [comment]
@Tushar98644 Create a seperate folder for BMI calci and put your both file in this folder.

**Comment by Tushar98644** [comment]
> @Tushar98644 Create a seperate folder for BMI calci and put your both file in this folder.

ok...

**Pull request closed without merging**
